# Configure Yarn to work with Cloudflare workers

nodeLinker: node-modules

enableGlobalCache: false

# Don't enforce the lock file on CI
enableImmutableInstalls: false

# Allow ignoring the lock file during installation
nmMode: hardlinks-local