name = "keiko"
compatibility_date = "2024-01-09"

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "${KV_ID}"

[vars]
PLAUSIBLE_DOMAIN = "${PLAUSIBLE_DOMAIN}"
TOKEN = "${TOKEN}"